title: pino44io

url: "https://pino44io.github.io" # the base hostname & protocol for your site
plugins:
  - jekyll-bookshop
  - cloudcannon-jekyll-bookshop
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-pagebreak
  - jekyll-include-cache

# Multiple bookshops can be used on one website,
# or different production / staging locations.
bookshop_locations:
  - ../components

exclude:
  - postcss.config.js
  - node_modules

include:
  - _cloudcannon

# The rest of this array structure will be
# populated by the bookshop-array-structures plugin.
_array_structures:
  content_blocks:
    style: modal

collections_dir: 'collections'

collections:
  pages:
    output: true
    permalink: /:title/
  posts:
    output: true
    permalink: /:categories/:slug
  albums:
    output: true
    permalink: /virtual-photography/:slug

cloudcannon:
  collections:
    pages:
      _icon: 'wysiwyg'
    testimonials:
      _icon: 'format_quote'
      _subtext_key: position
      _enabled_editors:
        - data

_collection_groups:
  - heading: Content
    collections:
      - pages
  - heading: Blogging
    collections:
      - posts
      - drafts
  - heading: Settings
    collections:
      - data

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: pages
      path: _pages/index.html
    values:
      permalink: /
  - scope:
      type: posts
    values:
      layout: post
  - scope:
      type: reviews
    values:
      layout: review
  - scope:
      type: albums
    values:
      layout: album

#sass:
#  sass_dir: _sass


# Tags
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: /:title
