[component]
structures = [ "content_blocks" ]
label = "Artworks"
description = "Artworks Section with heading, a description and a link"
icon = "wysiwyg"
tags = ["Content"]

[props]
title = "Latest Works"
description_html = "I show only my best works built completely with passion, simplicity, and creativity!"
link_url = "/Artworks"
show_Artworks = true